// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bioscoop_app.Model;

namespace bioscoop_app.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20200326203141_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("bioscoop_app.Model.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("duration");

                    b.Property<string>("genre");

                    b.Property<float>("rating");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("bioscoop_app.Model.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<double>("price");

                    b.HasKey("id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("bioscoop_app.Model.Ticket", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Productid");

                    b.Property<int>("visitor_age");

                    b.HasKey("id");

                    b.HasIndex("Productid");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("bioscoop_app.Model.Ticket", b =>
                {
                    b.HasOne("bioscoop_app.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Productid");
                });
#pragma warning restore 612, 618
        }
    }
}
